apiVersion: v2
name: keystone
description: A Helm chart for Openstack Keystone
type: application
version: 2.1.2
appVersion: 27.0.0-41-g15a9172cf-2-12
dependencies:
- name: nectarlib
  version: 4.0.1
  repository: oci://registry.rc.nectar.org.au/nectar-helm
