apiVersion: v2
name: keystone
description: A Helm chart for Openstack Keystone
type: application
version: 1.0.6
appVersion: 25.0.0-18-ge05f7feca-7-12
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.3
- name: nectarlib
  version: 3.1.4
  repository: oci://registry.rc.nectar.org.au/nectar-helm
